# Generated by Django 4.2 on 2023-05-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desccription',
            new_name='description',
        ),
    ]
